services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - app_storage:/app/storage/app/public
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

volumes:
  app_storage: